set nocompatible                " use vim settings over vi
syntax on
set background=dark
syntax enable                   " turn on syntax highlighting
set encoding=utf-8
set showcmd                     " bottom line will show information about command
filetype plugin indent on       " load file type plugins + indentation
set history=50                  " save 50 lines of history
set ruler                       " ruler
set number                      " show line numbers
set cursorline                  " highlight current line
set wildmenu                    " visual autocomplete for command menu
set modeline
set autowrite
execute pathogen#infect()

set nowrap                      " do not wrap lines
set tabstop=2 shiftwidth=2      " tab is two spaces
set expandtab                   " tabs are spaces
set backspace=indent,eol,start  " backspace through everything
set backspace=2

set hlsearch                    " highlight matches when searching
set incsearch                   " incremental searching
set ignorecase                  " searches ignore case
set smartcase                   " unless the search contains 1+ capital letter

let g:dracula_colorterm = 0
colorscheme dracula
let g:rehash256 = 1
" let g:molokai_original = 1
"colorscheme molokai

set laststatus=2

:tab sball

let mapleader = ","
let maplocalleader = ",,"

nnoremap <Leader>f :NERDTreeToggle<Enter>
let NERDTreeQuitOnOpen = 1
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeShowHidden=1

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" format with goimports instead of gofmt
let g:go_fmt_command = "goimports"

map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>
autocmd FileType go nmap <leader>r <Plug>(go-run)
autocmd FileType go nmap <leader>t <Plug>(go-test)
autocmd FileType go nmap <leader>c <Plug>(go-coverage-toggle)
" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4

autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')
autocmd FileType go nmap <Leader>i <Plug>(go-info)
let g:go_auto_sameids = 1

let g:vim_markdown_folding_disabled = 1

let g:WMGraphviz_output="png"
let g:WMGraphviz_viewer="firefox"
