#!/usr/bin/env sh

# Catppuccin mocha
text='9399b2' # overlay2
black='1F1E2F'
green='a6e3a1'
purple='b4befe'
blue='89b4fa'
white='cdd6f4'

spacebar -m config position                    top
spacebar -m config height                      26
spacebar -m config title                       off
spacebar -m config spaces                      on
spacebar -m config clock                       on
spacebar -m config power                       on
spacebar -m config padding_left                20
spacebar -m config padding_right               20
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "Inconsolata:Bold:12.0"
spacebar -m config icon_font                   "Font Awesome 6 Free:Solid:12.0"
spacebar -m config background_color            0xff$black
spacebar -m config foreground_color            0xff$text
spacebar -m config power_icon_color            0xff$green
spacebar -m config battery_icon_color          0xff$text
spacebar -m config dnd_icon_color              0xff$purple
spacebar -m config clock_icon_color            0xff$text
spacebar -m config power_icon_strip             
spacebar -m config space_icon                  •
spacebar -m config space_icon_color            0xffffab91
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
spacebar -m config space_icon_strip            1 2 3 4 5 6 7 8 9 10
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%Y-%m-%d %R"
spacebar -m config right_shell                 off

echo "spacebar configuration loaded.."
