# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="steeef"
#ZSH_THEME="random"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(aws git battery kubectl zsh-autosuggestions fzf kube-ps1 asdf)

# User configuration

export GOPATH=~/go

source $ZSH/oh-my-zsh.sh
source <(helm completion zsh)
if [[ $(uname) == "Linux" ]]; then
  source /opt/kube-ps1/kube-ps1.sh
elif [[ $(uname) == "Darwin" ]]; then
  source /opt/homebrew/opt/kube-ps1/share/kube-ps1.sh
  . /opt/homebrew/opt/asdf/libexec/asdf.sh
fi
KUBE_PS1_SYMBOL_ENABLE=false
KUBE_PS1_PREFIX="(k: "
SHOW_AWS_PROMPT=false
RPROMPT="${RPROMPT//\$\(aws_prompt_info\)}"
ZSH_THEME_AWS_PROFILE_PREFIX="(a: "
ZSH_THEME_AWS_PROFILE_SUFFIX=") "
ZSH_THEME_AWS_REGION_PREFIX="(r: "
ZSH_THEME_AWS_REGION_SUFFIX=") "
# You may need to manually set your language environment
export LANG=en_US.UTF-8

export EDITOR='vim'
# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias k="kubectl"
alias describe="k describe"
alias get="k get"
alias create="k create"
alias apply="k apply"
alias delete="k delete"
alias logs="k logs"
alias pods="get pods"
alias services="get svc"
alias deployments="get deployments"
alias replicasets="get rs"
alias replicationcontrollers="get rc"
alias rc="get rc"
alias nodes="get nodes"
alias limitranges="get limitranges"
alias limits="get limitranges"
alias events="get events"
alias persistentvolumes="get pv"
alias pv="get pv"
alias persistentvolumeclaims="get pvc"
alias pvc="get pvc"
alias namespaces="get ns"
alias ingresses="get ing"
alias ing="get ing"
alias configmaps="get configmaps"
alias secrets="get secrets"
alias sandbox="kubectl config use-context sandbox"
alias development="kubectl config use-context development"
alias staging="kubectl config use-context staging"
alias production="kubectl config use-context production"
alias shared="kubectl config use-context shared"
alias tf="terraform"
alias vim="nvim"

DEFAULT_USER=miles

function sunglasses() {
  echo -en " ( •_•)     \r"; sleep .5;
  echo -en " ( •_•)>⌐■-■\r"; sleep 1;
  echo     " (⌐■_■)     ";   sleep 1;
}

function stopwatch() {
  start=$(date +%s)
  while true; do
      time="$(($(date +%s) - $start))"
      printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
  done
}

export BROWSER=google-chrome

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export GTK_THEME="Catppuccin-Mocha"
export XDG_SCREENSHOTS_DIR=~/screenshots

export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
